accordion/urls.py
from django.urls import path
from . import views

app_name = "accordion"

urlpatterns = [
    path('', views.home, name='accordion'),
]

catatkegiatan/urls.py
from django.urls import path
from . import views

app_name = "catatkegiatan"

urlpatterns = [
    path('', views.home, name='catatkegiatan'),
    path('tambahkegiatan', views.tambahkegiatan, name='tambahkegiatan'),
    path('tambahpeserta/<int:id>', views.tambahpeserta, name='tambahpeserta'),
]

catatmatkul/urls.py
from django.urls import path

from . import views

app_name = 'catatmatkul'

urlpatterns = [
    path('', views.home, name='catatmatkul'),
    path('lihat', views.lihatmatkul, name="lihatmatkul"),
    path('lihat/<int:id>', views.detailmatkul, name="detailmatkul"),
    path('tambah', views.tambahmatkul, name="tambahmatkul"),
    path('hapus', views.hapusmatkul, name="hapusmatkul"),
    path('hapus/<int:id>', views.konfirmasihapus, name="konfirmasihapus"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('porto', views.porto, name='porto'),
    path('story1', views.story1, name='story1'),
]

menyapa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='menyapa'),
    path('masuk', views.masuk, name='masuk'),
    path('keluar', views.keluar, name='keluar'),
    path('daftar', views.daftar, name='daftar'),
    path('gagal', views.gagal, name='gagal'),
]

storyppwhafizh/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catatmatkul/', include('catatmatkul.urls')),
    path('catatkegiatan/', include('catatkegiatan.urls')),
    path('accordion/', include('accordion.urls')),
    path('menyapa/', include('menyapa.urls')),
    path('', include('main.urls')),
]

accordion/models.py
from django.db import models

# Create your models here.

catatkegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.nama

class Peserta(models.Model):
    nama = models.CharField(max_length=20)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.nama

catatmatkul/models.py
from django.db import models

class Matkul(models.Model):
    nama = models.CharField(max_length=30)
    dosen_pengajar = models.CharField(max_length=30)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    semester_tahun = models.CharField(max_length=15)
    ruang_kelas = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.nama

main/models.py
from django.db import models

# Create your models here.

menyapa/models.py
from django.db import models

# Create your models here.

catatkegiatan/forms.py
from django import forms
from django.forms import fields
from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'

catatmatkul/forms.py
from django.forms import ModelForm
from .models import Matkul

class MatkulForm(ModelForm):
    class Meta:
        model = Matkul
        fields = '__all__'

accordion/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'accordion/home.html')

catatkegiatan/views.py
from catatkegiatan.forms import KegiatanForm, PesertaForm
from catatkegiatan.models import Kegiatan, Peserta
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
    daftar_kegiatan = Kegiatan.objects.all().values()
    dict_kegiatan = {}
    for kegiatan in daftar_kegiatan:
        daftar_peserta = Peserta.objects.filter(kegiatan = kegiatan['id']).values()
        dict_kegiatan[kegiatan['id']] = {
            'id' : kegiatan['id'],
            'nama' : kegiatan['nama'],
            'peserta' : [peserta for peserta in daftar_peserta]
        }
    return render(request, 'catatkegiatan/index.html', {'dict_kegiatan' : dict_kegiatan.items()})

def tambahkegiatan(request):
    form = KegiatanForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('/catatkegiatan')
    else:
        return render(request, 'catatkegiatan/tambahkegiatan.html', {'form' : form})

def tambahpeserta(request, id):
    form = PesertaForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('/catatkegiatan')
    else:
        context = {
            'form' : form,
            'id' : id,
            'namakegiatan' : Kegiatan.objects.values().get(pk=id)['nama'],
        }
        return render(request, 'catatkegiatan/tambahpeserta.html', context)

catatmatkul/views.py
from django.http import response
from django.shortcuts import redirect, render
from .models import Matkul
from catatmatkul.forms import MatkulForm

def home(request):
    return render(request, 'catatmatkul/index.html')

def lihatmatkul(request):
    matkuls = Matkul.objects.values()
    response = {}
    response['matkuls'] = matkuls
    return render(request, 'catatmatkul/lihatmatkul.html', response)

def detailmatkul(request, id):
    matkul = Matkul.objects.values().get(pk=id)
    return render(request, 'catatmatkul/detailmatkul.html', matkul)

def tambahmatkul(request):
    form = MatkulForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form = MatkulForm(request.POST)
        form.save()
        return redirect('/catatmatkul/lihat')
    else:
        return render(request, 'catatmatkul/tambahmatkul.html',{'form':form})

def hapusmatkul(request):
    matkuls = Matkul.objects.values()
    response = {}
    response['matkuls'] = matkuls
    return render(request, 'catatmatkul/hapusmatkul.html', response)

def konfirmasihapus(request, id):
    if request.method == "POST":
        matkul = Matkul.objects.get(pk=id)
        matkul.delete()
        return redirect('/catatmatkul/hapus')
    matkul = Matkul.objects.values().get(pk=id)
    return render(request, 'catatmatkul/konfirmasihapus.html', matkul)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def porto(request):
    return render(request, 'main/porto.html')

def story1(request):
    return render(request, 'main/story1.html')

menyapa/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    return render(request, 'menyapa/home.html')

def masuk(request):
    if (request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if (user is not None):
            login(request, user)
            return redirect('/menyapa')
        else:
            return redirect('/menyapa/gagal')
    else:
        return render(request, 'menyapa/login.html')

def gagal(request):
    return render(request, 'menyapa/gagal.html')

def daftar(request):
    if (request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.create_user(username, '', password)
        login(request, user)
        return redirect('/menyapa')
    else:
        return render(request, 'menyapa/register.html')

def keluar(request):
    logout(request)
    return redirect('/menyapa')

accordion/templates/accordion/home.html
{% extends 'base_story7.html' %}
{% load static %}

{% block meta %}
<title>Accordion</title>
{% endblock meta %}

{% block content %}
<h1>Accordion</h1> <br><br>

<div>
    <div class="accordion">Aktivitas saat ini
        <div class="tombolnaikturun">
            <button class="btn btn-primary naik">↑</button>
            <button class="btn btn-danger turun">↓</button>
        </div>
    </div>
    <div class="panel">
        <div class="space18"></div>
        <p>Saat ini saya sedang berkuliah di jurusan sistem informasi, Fasilkom UI</p>
    </div>
</div>
<div>
    <div class="accordion">Pengalaman organisasi/kepanitiaan
        <div class="tombolnaikturun">
            <button class="btn btn-primary naik">↑</button>
            <button class="btn btn-danger turun">↓</button>
        </div>
    </div>
    <div class="panel">
        <div class="space18"></div>
        <ul>
            <li>RISTEK Fasilkom UI
                <ul>
                    <li>Member of Mobile Development (Mar 2021 - Present)</li>
                    <li>Member of Competitive Programming SIG (Feb 2020 - Jan 2021)</li>
                </ul>
            </li>
            <li>Minang Culture Festival IMAMI UI
                <ul>
                    <li>Head of Public Relation, Publication, and Media Partner (Feb 2021 - Present)</li>
                    <li>Staff of Design Team (Feb 2020 - Apr 2020)</li>
                </ul>
            </li>
            <li>Cerita Kita UI
                <ul>
                    <li>Head of Design Team (Aug 2020 - Dec 2020)</li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<div>
    <div class="accordion">Pendidikan
        <div class="tombolnaikturun">
            <button class="btn btn-primary naik">↑</button>
            <button class="btn btn-danger turun">↓</button>
        </div>
    </div>
    <div class="panel">
        <div class="space18"></div>
        <ul>
            <li>Universitas Indonesia - Jurusan Sistem Informasi (2019 - Present)</li>
            <li>SMA Negeri 1 Padang Panjang (2016 - 2019)</li>
            <li>MTs Negeri 1 Kota Bukittinggi (2013 - 2016)</li>
            <li>SD Islam Al-Ishlah Bukittinggi (2007 - 2013)</li>
            <li>TK Islam Excellent Bukittinggi (2005 - 2007)</li>
        </ul>
    </div>
</div>
<div>
    <div class="accordion">Prestasi
        <div class="tombolnaikturun">
            <button class="btn btn-primary naik">↑</button>
            <button class="btn btn-danger turun">↓</button>
        </div>
    </div>
    <div class="panel">
        <div class="space18"></div>
        <ul><li>Finalis OSN Informatika - Padang 2018</li></ul>
    </div>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/myScript.js' %}"></script>
{% endblock content %}

catatkegiatan/templates/catatkegiatan/index.html
{% extends 'base_story6.html' %}
{% load static %}

{% block meta %}
    <title>CatatKegiatan</title>
{% endblock meta %}

{% block content %}
    <h1>CatatKegiatan</h1> <br><br>
        <div class="container">
            <div class="row">
                {% for id, kegiatan in dict_kegiatan %}
                    <div class="card" style="width: 18rem; margin: 1rem;">
                        <h3 class="card-title" style="margin: 1rem; color: blueviolet;"> {{ kegiatan.nama }} </h3>
                        <ul class="list-group list-group-flush">
                            {% for peserta in kegiatan.peserta %}
                                <li class="list-group-item"> {{ peserta.nama}} </li>
                            {% endfor %}
                        </ul>
                        <a href="/catatkegiatan/tambahpeserta/{{ id }}" class="btn btn-primary" style="margin: 1rem;">Tambah Peserta</a>
                        <br>
                    </div>
                {% endfor %}
            </div>
        </div>
{% endblock content %}

catatkegiatan/templates/catatkegiatan/tambahkegiatan.html
{% extends 'base_story6.html' %}
{% load static %}

{% block meta %}
    <title>Tambah Kegiatan</title>
{% endblock meta %}

{% block content %}
    <h1>Tambah Kegiatan</h1>
    <form action="/catatkegiatan/tambahkegiatan" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Tambah">
    </form>
{% endblock content %}

catatkegiatan/templates/catatkegiatan/tambahpeserta.html
{% extends 'base_story6.html' %}
{% load static %}

{% block meta %}
    <title>Tambah Peserta</title>
{% endblock meta %}

{% block content %}
    <h1>Tambah Peserta {{ namakegiatan }}</h1>
    <form action="/catatkegiatan/tambahpeserta/{{ id }}" method="POST">
        {% csrf_token %}
        <tr>
            <th><label for="id_nama">Nama:</label></th>
            <td><input type="text" name="nama" maxlength="20" required id="id_nama"></td>
        </tr>
        <tr>
            <th><label for="id_kegiatan" hidden>Kegiatan:</label></th>
            <td><select name="kegiatan" required id="id_kegiatan" hidden>
                    <option value="{{ id }}" selected></option>
                </select></td>
        </tr>
        <input type="submit" value="Tambah">
    </form>
{% endblock content %}

catatmatkul/templates/catatmatkul/detailmatkul.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>Detail matkul {{ nama }}</title>
{% endblock meta %}

{% block content %}
    <h1>{{nama}}</h1> <br>
    Pengajar : {{ dosen_pengajar }} <br>
    Jumlah sks : {{ jumlah_sks}} <br>
    Deskripsi : {{ deskripsi}} <br>
    Semester / tahun ajaran : {{ semester_tahun}} <br>
    Ruang kelas : {{ ruang_kelas }} <br>

{% endblock content %}

catatmatkul/templates/catatmatkul/hapusmatkul.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>Hapus Matkul</title>
{% endblock meta %}

{% block content %}
    <h1>Hapus Matkul</h1>
    <br>
    {% if matkuls %}
        {% for matkul in matkuls %}
            <h3>{{ matkul.nama }}</h3>
            <a href="/catatmatkul/hapus/{{ matkul.id }}" class="btn btn-danger">Hapus</a>
            <br> <br>
        {% endfor %}
    {% endif %}
{% endblock content %}

catatmatkul/templates/catatmatkul/index.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>CatatMatkul</title>
{% endblock meta %}

{% block content %}
    <h1>CatatMatkul</h1>
    <a href="/catatmatkul/lihat" class="btn btn-primary">Lihat daftar matkul</a> <br>
    <a href="/catatmatkul/tambah" class="btn btn-info">Tambah matkul</a><br>
    <a href="/catatmatkul/hapus" class="btn btn-danger">Hapus matkul</a><br>
{% endblock content %}

catatmatkul/templates/catatmatkul/konfirmasihapus.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>Hapus matkul {{ nama }}</title>
{% endblock meta %}

{% block content %}
    <h1>Hapus matkul {{ nama }}?</h1> <br>
    <p>Apakah anda yakin akan menghapus matkul ini? Tindakan ini tidak dapat diurungkan</p>
    <a href="/catatmatkul/hapus" class="btn btn-primary">Batal</a>
    <form action="/catatmatkul/hapus/{{ id }}" method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" name="Hapus">
    </form>


{% endblock content %}

catatmatkul/templates/catatmatkul/lihatmatkul.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>Lihat Matkul</title>
{% endblock meta %}

{% block content %}
    <h1>List Matkul</h1>
    <br>
    {% if matkuls %}
        {% for matkul in matkuls %}
            <h3>{{ matkul.nama }}</h3>
            <a href="/catatmatkul/lihat/{{ matkul.id }}" class="btn btn-info">detail</a>
            <br/> <br>
        {% endfor %}
    {% endif %}
{% endblock content %}

catatmatkul/templates/catatmatkul/tambahmatkul.html
{% extends 'base_story5.html' %}
{% load static %}

{% block meta %}
    <title>Tambah Matkul</title>
{% endblock meta %}

{% block content %}
    <h1>Tambah Matkul</h1>
    <form action="/catatmatkul/tambah" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Tambah">
    </form>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>It's me! Hafizh Salam</title>
{% endblock meta %}

{% block content %}
  <div class="pages"  id="akuapiss">
        <div class="titledesc">
            <h1>Hai, aku Hafizh!</h1>
            <p>Perkenalkan aku Hafizh Salam, bisa panggil saja Hafizh. Saat ini aku sedang menjalani perkuliahan
                semester 4
                di
                jurusan Sistem Informasi di Universitas Indonesia</p>
        </div>
        <img src="{% static 'img/apis.png'%}" alt="Foto Saya" style="height: 25vw;">
    </div>

    <div class="pages">
        <img src="{% static 'img/logongodingweb.png' %}" style="height: 25vh;">
        <h1 style="margin-left: 10vw;">Saat ini aku sedang menjalani mata kuliah PPW</h1>
    </div>

    <div class="pages">
        <h1>Data diriku</h1>
        <div class="datadiri">
            <table>
                <tbody>
                    <tr>
                        <td>Nama</td>
                        <td>Hafizh Salam</td>
                    </tr>
                    <tr>
                        <td>TTL</td>
                        <td>Bukittinggi, 5 Agustus 2001</td>
                    </tr>
                    <tr>
                        <td>Alamat</td>
                        <td>Kamang Hilir, Kabupaten Agam, Sumatera Barat</td>
                    </tr>
                    <tr>
                        <td>Jurusan</td>
                        <td>Sistem Informasi</td>
                    </tr>
                    <tr>
                        <td>Hobi</td>
                        <td>Tidur</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

main/templates/main/porto.html
{% extends 'base.html'%}
{% load static %}

{% block meta %}
    <title>My Portofolio</title>
{% endblock meta %}

{% block content %}
    <div class="titlebar">
        <h1>My Portofolio</h1>
    </div>

    <div class="porto-box">
        <div class="porto-clmn">
            <img src="{% static 'img/porto/image 2.jpg'%}">
            <img src="{% static 'img/porto/image 4.png'%}">
            <img src="{% static 'img/porto/image 7.png'%}">
        </div>
        <div style="width: 10pt;"></div>
        <div class="porto-clmn">
            <img src="{% static 'img/porto/image 3.png'%}">
            <img src="{% static 'img/porto/image 5.png'%}">
            <img src="{% static 'img/porto/image 6.png'%}">
        </div>
    </div>
{% endblock content %}

main/templates/main/story1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 1</title>
</head>

<body>

</body>
<img src="{% static 'img/story1/story1.jpg' %}"
    alt="Foto Saya" width="400" style="border-radius: 50%;">
<h1>Tentang Saya</h1>
<p>Hai! Saya adalah seorang mahasiswa Fasilkom UI dan sekarang sedang menjalani semester 4</p>
<table>
    <tr>
        <td>Nama</td>
        <td>Hafizh Salam</td>
    </tr>
    <tr>
        <td>Angkatan</td>
        <td>2019</td>
    </tr>
    <tr>
        <td>Jurusan</td>
        <td>Sistem Informasi</td>
    </tr>
    <tr>
        <td>Hobi</td>
        <td>Tidur</td>
    </tr>
</table>
<br><br>
<h3>Media Sosial</h3>
<table>
    <tr>
        <td>
            <a href="https://fb.me/hafizh.salam">
                <img src="{% static 'img/story1/fb.svg' %}"
                    alt="Facebook" width="30">
            </a>
        </td>
        <td>
            <a href="https://instagram.com/pislm">
                <img src="{% static 'img/story1/ig.png' %}" alt="Instagram" width="30">
            </a>
        </td>
        <td>
            <a href="https://twitter.com/hfslm">
                <img src="{% static 'img/story1/twt.png' %}" alt="Twitter"
                    width="30">
            </a>
        </td>
        <td>
            <a href="https://www.linkedin.com/in/hafizhsalam/">
                <img src="{% static 'img/story1/lin.png' %}" alt="LinkedIn"
                    width="30">
            </a>
        </td>
        <td>

        </td>
    </tr>
</table>

</html>

menyapa/templates/menyapa/gagal.html
{% extends 'base_story9.html' %}
{% load static %}

{% block meta %}
    <title>Ups</title>
{% endblock meta %}

{% block content %}
    <h1> Ups! </h1> <br>
    <p> Sepertinya username atau password kamu salah, atau kamu belum terdaftar? </p>
    <a href="/menyapa/masuk" class="btn btn-primary">Masuk</a>
    <a href="/menyapa/daftar" class="btn btn-success">Daftar</a>
{% endblock content %}

menyapa/templates/menyapa/home.html
{% extends 'base_story9.html' %}
{% load static %}

{% block meta %}
    <title>Menyapa</title>
{% endblock meta %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Halo {{ user.username }}!</h1> <br>
        <a href="/menyapa/keluar" class="btn btn-danger">Log out</a>
    {% else %}
        <h1>Halo orang asing!</h1> <br>
        <p>Sepertinya kamu belum masuk, silakan coba beberapa pilihan berikut</p>
        <a href="/menyapa/masuk" class="btn btn-primary">Masuk</a>
        <a href="/menyapa/daftar" class="btn btn-success">Daftar</a>
    {% endif %}
{% endblock content %}

menyapa/templates/menyapa/login.html
{% extends 'base_story9.html' %}
{% load static %}

{% block meta %}
    <title>Menyapa</title>
{% endblock meta %}

{% block content %}
    <h1>Login</h1>
    <form action="/menyapa/masuk" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username"> <br>
        <label for="password">Password</label>
        <input type="password" name="password" id="password"> <br>
        <input type="submit" value="Login" class="btn btn-primary">
    </form>
{% endblock content %}

menyapa/templates/menyapa/register.html
{% extends 'base_story9.html' %}
{% load static %}

{% block meta %}
    <title>Menyapa</title>
{% endblock meta %}

{% block content %}
    <h1>Daftar akun</h1>
    <form action="/menyapa/daftar" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username"> <br>
        <label for="password">Password</label>
        <input type="password" name="password" id="password"> <br>
        <input type="submit" value="Daftar" class="btn btn-primary">
    </form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <ul class="topnav">
        <li id="navhome"><a href="/">Hafizh Salam</a></li>
        <li id="navpages"><a href="/porto">Portofolio</a></li>
        <li id="navpages"><a href="/">About Me</a></li>
        <li id="navpages"><a href="/story1">Story 1</a></li>
    </ul>
    <div style="height: 55pt;"></div>
  {% block content %}
  {% endblock content %}
  <div class="kontak">
        <h2>Temukan aku di</h2>
        <div>
            <a href="https://fb.com/hafizh.salam"><img src="{% static 'img/social/facebook.svg' %}" alt="" id="ikonsosmed"></a>
            <a href="https://instagram.com/pislm"><img src="{% static 'img/social/instagram.svg' %}" alt="" id="ikonsosmed"></a>
            <a href="https://twitter.com/hfslm"><img src="{% static 'img/social/twitter.svg' %}" alt="" id="ikonsosmed"></a>
            <a href="https://linkedin.com/in/hafizhsalam"><img src="{% static 'img/social/linkedin.svg' %}" alt="" id="ikonsosmed"></a>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>